# ref: https://jupyterbook.org/en/stable/customize/config.html

title: Paper
author: Maya Niyogi
execute:
  execute_notebooks: force

bibtex_bibfiles:
  - References_MNiyogi.bib

sphinx:
  config:
    bibtex_reference_style: author_year
